### ISSUE TITLE
Add new line at end of output?

### ISSUE THREAD

**Issue by wezm** [scruffystuffs/jfmt.rs#1]
It seems that `jfmt` does not write a newline at the end of its output, as is typically done. My shell (`zsh`) makes me aware of this with an inverted `%` at the end of any output that doesn't end in a new line:

<img width="358" alt="Screenshot from 2022-02-09 17-07-28" src="https://user-images.githubusercontent.com/21787/153139368-ddb3d272-81df-421d-b103-43b7a168ba4a.png">

Compare `jq`:

<img width="352" alt="Screenshot from 2022-02-09 17-10-36" src="https://user-images.githubusercontent.com/21787/153139782-cd1ce5ea-df79-4696-9f2a-4a22b1bcddb1.png">

Perhaps this could be added?

**Comment by skilly-lily** [comment]
Interesting, I'm not sure why I hadn't caught that before.  I'll make this change soon.

**Comment by skilly-lily** [comment]
This was predictably a trivial fix, but I need a feature to add to test the release automation I'm working on.  So this is gonna delay until I finish that up.

**Comment by skilly-lily** [comment]
Fixed in v1.2.1
