### ISSUE TITLE
AUR package

### ISSUE THREAD

**Issue by wezm** [scruffystuffs/jfmt.rs#2]
Howdy (always good to encounter another Rust-writing Wesley). This issue is just to mention that I created an AUR package for `jfmt`. Sometime folks mention this in the README, but that can be the road to madness (E.g. see [the giant list of packages ripgrep has accumulated](https://github.com/BurntSushi/ripgrep/blob/0b36942f680bfa9ae88a564f2636aa8286470073/README.md#installation)), so up to you. 👍 

https://aur.archlinux.org/packages/jfmt

**Comment by skilly-lily** [comment]
I'll drop this in the README, and mention that it's maintained by someone else.  Want me to link you in the README or no?

**Comment by wezm** [comment]
> I'll drop this in the README, and mention that it's maintained by someone else.

Cool 

>  Want me to link you in the README or no?

Nah, it lists me as maintainer on the AUR page and it's not all that uncommon for my AUR packages to be picked up by an [Arch trusted user](https://wiki.archlinux.org/title/Trusted_Users) and get promoted to the community repo (at which point I'm no longer the maintainer).

**Comment by skilly-lily** [comment]
Added in da68338

**Comment by psibi** [comment]
I guess it adds value to add repology badge to include the packaging status: https://repology.org/project/jfmt/badges

I have added it this to nixpkgs recently (https://github.com/NixOS/nixpkgs/pull/159164) and I believe in some days the repology will get updated with the appropriate entry for nixpkgs-unstable.
